(in-package #:with-c-syntax.stdlib)

(defun va_start (ap last)
  (declare (ignorable last))
  (unless (length= ap 1)
    (error "va_start: bad args: (~S, ~S)" ap last))
  `(get-varargs ,(first ap)))

(defun va_arg (ap type)
  (declare (ignorable type))
  (unless (length= ap 1)
    (error "va_arg: bad args: (~S, ~S)" ap type))
  `(pop ,(first ap)))

(defun va_end (ap)
  (unless (length= ap 1)
    (error "va_end: bad args: (~S)" ap))
  `(setf ,(first ap) nil))

(defun va_copy (dest src)
  (unless (and (length= dest 1)
               (length= src 1))
    (error "va_copy: bad args: (~S, ~S)" dest src))
  `(setf ,(first dest) (copy-list ,(first src))))

(eval-when (:load-toplevel :execute)
  (define-predefined-typedef-and-aliases '|va_list| 'list
    '(|VA_LIST| |va_list|))
  (define-preprocessor-symbol '|VA_START| #'va_start)
  (define-preprocessor-symbol '|va_start| #'va_start)
  (define-preprocessor-symbol '|VA_ARG| #'va_arg)
  (define-preprocessor-symbol '|va_arg| #'va_arg)
  (define-preprocessor-symbol '|VA_END| #'va_end)
  (define-preprocessor-symbol '|va_end| #'va_end)
  (define-preprocessor-symbol '|VA_COPY| #'va_copy)
  (define-preprocessor-symbol '|va_copy| #'va_copy)
  )
