(in-package #:with-c-syntax.stdlib)

(eval-when (:load-toplevel :execute)
  (define-predefined-typedef-and-aliases '|bool| 'boolean '(|bool| |BOOL|))
  (define-preprocessor-symbol '|__bool_true_false_are_defined| 1)
  (define-preprocessor-symbol '|true| '(and))
  (define-preprocessor-symbol '|false| '(or))
  (define-preprocessor-symbol '|TRUE| '(and))
  (define-preprocessor-symbol '|FALSE| '(or))
  )
