(in-package #:with-c-syntax.stdlib)

(eval-when (:load-toplevel :execute)
  (define-preprocessor-macro "NULL" 0)
  (define-predefined-typedef-and-aliases '|ptrdiff_t| 'fixnum)
  (define-predefined-typedef-and-aliases '|size_t| 'fixnum)
  (define-predefined-typedef-and-aliases '|wchar_t| 'fixnum)
  (define-preprocessor-macro "OFFSETOF" 'with-c-syntax::|__offsetof| t)
  (define-preprocessor-macro "offsetof" 'with-c-syntax::|__offsetof|)
  )
